### ISSUE TITLE
[Effect Suggestion] Rick roll qr code

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#494] opened 2021-02-01 13:35 UTC
**Name of effect**
Potential name(s) for the effect
QR CODE
**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
short

**Effect Description**
Description of the effect; what should it do?

put a rickroll qr code on the screen

**Comment by anto4440** [comment] 2021-02-01 13:44
Again, no. duplicate of #486

**Comment by ThatDeathbat** [comment] 2021-02-01 19:02
Pretty bad idea.

**Comment by Last0xygen** [comment] 2021-02-02 18:22
This is not really interesting. After seeing it once the "fun" is gone, sorry

**Closed by Last0xygen** 2021-02-02 18:22 UTC
Labels: Effect Suggestion
