### ISSUE TITLE
[Effect Suggestion] Transform into animal

### ISSUE THREAD

**Issue by Trumzy** [gta-chaos-mod/ChaosModV#356] opened 2021-01-15 15:38 UTC
**Name of effect**
Animal Transformation
Animal Morph
Peyote Addict
Rob Schneider is The Animal

**Duration if timed effect (long or short timed?)**
60 seconds

**Effect Description**
Temporarily change player model into a random animal model

**Comment by Trumzy** [comment] 2021-01-15 15:41
Noticed it was similar to the effect animal kingdom thats already been suggested, however only effects the player not all peds.

**Comment by Terrain2** [comment] 2021-01-15 23:22
duplicate of #126

**Comment by EliRickard** [comment] 2021-01-16 06:27
Can cause countless problems, throughout game play, with soft lock potential, I can really only see this being viable if the player is in freemode.

**Comment by Last0xygen** [comment] 2021-03-01 21:41
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/126 https://github.com/gta-chaos-mod/ChaosModV/issues/260 https://github.com/gta-chaos-mod/ChaosModV/issues/253

**Closed by Last0xygen** 2021-03-01 21:41 UTC
Labels: Effect Suggestion
