### ISSUE TITLE
[Feature Suggestion] Long Lasting Effects

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1662] opened 2021-06-29 15:37 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, it sucks that an effect only lasts for 30-90 seconds. Dont get me wrong, 90% of the time it is for the best, but sometimes it creates this situation where you fight so hard to get past something only for the effect to wear off, rendering your hard work useless.

**Describe the solution you'd like**
Introducing the Long Lasting Effects, a smart way to make your hard work count to the fullest. The way it works is: Some effects get labeled as long lasting. It will only work on stat changing effects. An example could be: "your base health increases the more damage you take" After the effect, you no longer get to use your 'hard earned' high base health. This is the concept: making these value changes last for a long time. Stuff like:

- Base health (essentually your max health)
- Speed
- Damage (This stat is simple: Every time you deal damage, the damage you deal is multiplied by this stat. Example: 100 * 125% = 125 Damage dealt)
- Min Damage (if the damage you deal is less than this number, it will automatically round it up to this number)
- Max Damage (If the damage you deal exceeds this number, it will automatically round down to this number)
- Health (your Active health. Cannot exceed your base health. The player dies when this number hits 0)

With these Four attributes, we can immedeatly make the following effects:

- Increase Base health by 25
- Increase Base health by 25%
- Increase Base health by 50%
- Increase Base health by 100%
- Decrease Base health by 25
- Decrease Base health by 25%
- Decrease Base health by 50%
- Decrease Base health by 100%
- Set Base Health Back to stock

- Increase Speed by 25%
- Increase Speed by 50%
- Decrease Speed by 25%
- Decrease Speed by 50%
- Set Base Speed to Stock

- Increase Damage by 25%
- Increase Damage by 50%
- Increase Damage by 75%
- Decrease Damage by 25%
- Decrease Damage by 50%
- Decrease Damage by 75%
- Increase Min Damage by 25
- Decrease Min Damage by 25
-Increase Max Damage by 25
-Decrease Max Damage by 25

-Set Health to 10% of Base Health
-Set Health to 50% of Base Health
-Set Health to 100% of Base Health (Aka "Full Health")

**Additional context**
You should REALLY make it so that only one of these effects become possible per vote (If twitch controls are turned on). You could also make a 5. vote every second vote that would specifically be for these effects. And finally: Other value changing effects will also affect this. Which ones are up to you/The creators of them.

**Comment by anto4440** [comment] 2021-06-29 16:51
I forgot to mention that its impotant to have an effect that resets all the stats to their base

**Comment by SeanMirrsen** [comment] 2021-06-29 19:55
So... it's less a feature suggestion, and more an effect suggestion that requires a feature?

I already proposed widening the selection of default effect times in #593 , including allowing effects to have custom lengths by default, without having to be set by a user.

**Comment by anto4440** [comment] 2021-06-29 19:57
> So... it's less a feature suggestion, and more an effect suggestion that requires a feature?
> 
> I already proposed widening the selection of default effect times in #593 , including allowing effects to have custom lengths by default, without having to be set by a user.

Nono, it is the Feature itself that im suggesting.

**Comment by SeanMirrsen** [comment] 2021-06-29 20:34
> Nono, it is the Feature itself that im suggesting.

That would make it a duplicate of #593 . Expanding default timer lengths presets, adding custom timer lengths into the defaults, etc.

Your effect(s) suggestion(s) could be streamlined into one extra-long effect called "Life is a Game" or "RPG Elements", where doing things like killing people, destroying cars, and especially completing missions ticks up an internal "experience" counter, and periodically buffs you as you reach higher and higher thresholds, simultaneously healing you (i.e. the normal "level up" deal in many of the simpler ARPGs). Once the effect runs out, you're back to base stats.

**Comment by anto4440** [comment] 2021-06-29 20:36
Youre actually right... Except for the whole 'That would make it a duplicate of #593 . Expanding default timer lengths presets, adding custom timer lengths into the defaults, etc.

Your effect(s) suggestion(s) could be streamlined into one extra-long effect called "Life is a Game" or "RPG Elements", where doing things like killing people, destroying cars, and especially completing missions ticks up an internal "experience" counter, and periodically buffs you as you reach higher and higher thresholds, simultaneously healing you (i.e. the normal "level up" deal in many of the simpler ARPGs). Once the effect runs out, you're back to base stats.' part.

**Comment by SeanMirrsen** [comment] 2021-06-29 20:55
Well what is your actual suggestion then? Does it involve allowing effects to run for arbitrary amounts of time, rather than the preset "short/long" durations? Because #593 covers that.

**Comment by anto4440** [comment] 2021-06-29 21:02
> Well what is your actual suggestion then? Does it involve allowing effects to run for arbitrary amounts of time, rather than the preset "short/long" durations? Because #593 covers that.

Doesnt make it a dupe though... besides, it is only for specific type effects that extended duration works

**Comment by SeanMirrsen** [comment] 2021-06-29 21:18
Uh... no? Custom duration works for literally any non-instant effect. It actually works *right now*, you can set it in the settings app. All that's missing is the ability to have certain effects have a custom length by default.

**Comment by anto4440** [comment] 2021-06-29 21:23
I think you misunderstood me here: Im referring to *this* suggestion, not #539.

**Comment by SeanMirrsen** [comment] 2021-06-29 22:17
> I think you misunderstood me here: Im referring to _this_ suggestion, not #539.

Okay, but *what is this suggestion then*? Is it a feature request or an effect suggestion?

The feature you're asking for in the post, is a duplicate of feature request #593 - being able to set default effect lengths beyond the "short/long" options. The user can already set specific effects to be as long or short as they want, but the "default" data structure doesn't support it, and so effects can't have custom default lengths unless that feature is added.

The effects you're asking for, can be done, especially as a custom effect group. But, they will require the described feature to be added first, otherwise they would be too short to be of meaningful value.

**Comment by Last0xygen** [comment] 2021-06-30 05:03
Adding effects like „increase damage by 25%“ is not a good effect, as it doesn’t have any real effect on the game for 99.999%
yes you can kill faster but there are other effects for that too (also increase hp and so on).

making timers dynamic has already been suggested by the other request (#539)

**Closed by Last0xygen** 2021-06-30 05:04 UTC
Labels: Feature Request

**Comment by anto4440** [comment] 2021-06-30 06:40
Oh dear Lord… i nevet intended custom timer lengths. They have been there for so Long, and i am fully Aware of Them. My suggestion is for certain effects to not have an end timer at all. As for bad effects, it’s simple: don’t implement them. When I make these types of suggestions, stuff like that is ideas; not requirements.

Sendt fra min iPhone

**Comment by SeanMirrsen** [comment] 2021-06-30 09:35
> Oh dear Lord… i nevet intended custom timer lengths. They have been there for so Long, and i am fully Aware of Them. My suggestion is for certain effects to not have an end timer at all. As for bad effects, it’s simple: don’t implement them. When I make these types of suggestions, stuff like that is ideas; not requirements.

Okay, first point: this is the first I hear of the effects *not ending*. Closest you've said was that the effects should "last a long time", which is very distinctly different from "having no end time". 

Technically it could easily be achieved by setting a custom duration on the scale of IRL days, but a specific class of effect that doesn't display a timer yet is constantly active until otherwise dismissed could be useful in some cases. If you rename the suggestion to better reflect this, and clarify the description, it can probably be re-opened.

These "permanent" effects (not to be confused with effects set as permanent in the settings), if there are multiple different kinds, could warrant adding a new effect called "wipe random permanent", which would do as its name suggests.

-----
As for the effects you propose, I think they're probably still better off as a single effect, rather than multiple effects that are voted on. It makes the effect easier to track and dismiss, if need be, and allows it to do more interesting things than just effect changes from voted effects - such as adding new bonuses from experience or fulfilling missions or whatnot.

**Comment by anto4440** [comment] 2021-06-30 12:18
Yeah. Im very sorry for not being clear about this. Thats on me. I will try to rephrase my suggestion, and hope that these issues wont arrrive on the future again.
