### ISSUE TITLE
[Effect Suggestion] spawn companion griffer Jesus

### ISSUE THREAD

**Issue by Defalt333** [gta-chaos-mod/ChaosModV#896] opened 2021-03-28 10:55 UTC
spawn companion griffer Jesus

**Effect Description**
Spawn companion griffer Jesus that follow the player and have a railgun (And it's also a good way to scare Matt when he spawn)

**Comment by TheRealAyCe** [comment] 2021-03-28 16:55
Like this? https://github.com/gta-chaos-mod/ChaosModV/issues/565 many duplicates for this one i think

**Comment by Last0xygen** [comment] 2021-03-30 18:21
yup, duplicate of #565 and #391

**Closed by Last0xygen** 2021-03-30 18:21 UTC
Labels: Effect Suggestion
