### ISSUE TITLE
[Effect Suggestion] fake waypoint

### ISSUE THREAD

**Issue by Billion3000** [gta-chaos-mod/ChaosModV#2354] opened 2021-09-15 14:03 UTC
Name of effect
Fake waypoint

Duration (choose one and replace the corresponding "[ ]" with "[X]")

 Long :
 Short : V
 No duration :
Effect Description
You got teleported to waypoint , but just 5 or maybe 8 seconds

**Comment by kolyaventuri** [comment] 2021-09-15 14:59
Duplicate of #1625, #985, #747

**Closed by kolyaventuri** 2021-09-15 14:59 UTC
Labels: Effect Suggestion
