### ISSUE TITLE
[Effect Suggestion] prisoner

### ISSUE THREAD

**Issue by Pevetti** [gta-chaos-mod/ChaosModV#1794] opened 2021-07-12 17:41 UTC
**Name of effect**
Prisoner, prisoned

**Effect Description**
teleports player to the prison (in the desert) and changes outfit to orange prison outfit

**Comment by anto4440** [comment] 2021-07-12 19:12
Dupe of #1181

**Comment by Last0xygen** [comment] 2021-07-12 19:22
Duplicate

**Closed by Last0xygen** 2021-07-12 19:22 UTC
Labels: Effect Suggestion
