### ISSUE TITLE
[Effect Suggestion] Spawn Fake Greifer Jesus

### ISSUE THREAD

**Issue by M0SS-A55455IN** [gta-chaos-mod/ChaosModV#908] opened 2021-03-30 14:51 UTC
**Name of effect**
Spawn Vespucci Greifer Jesus

**Effect Description**
It summons Griefer Jesus but it's a fake 😂

**Comment by Last0xygen** [comment] 2021-03-30 18:21
duplicate of #565, #391 and #896

**Closed by Last0xygen** 2021-03-30 18:21 UTC
Labels: Effect Suggestion
