### ISSUE TITLE
[Effect Suggestion] Random Cutscene

### ISSUE THREAD

**Issue by ERV11** [gta-chaos-mod/ChaosModV#1928] opened 2021-07-26 18:49 UTC
Plays a random cutscene. Possibly make the cutscene end after 10 or so seconds if the cutscene is too long

**Comment by kolyaventuri** [comment] 2021-07-26 19:16
Duplicate of #532. 

FWIW, I have played around with this idea, but there's some complexities in getting the cutscene to play properly.

**Closed by kolyaventuri** 2021-07-26 19:16 UTC
Labels: Effect Suggestion
