### ISSUE TITLE
Spawn Companion Jesus

### ISSUE THREAD

**Issue by Aljotzi** [gta-chaos-mod/ChaosModV#910] opened 2021-03-30 18:35 UTC
Spawn Companion Jesus 

Takes effect instantly

Spawns a friendly Jesus with a Railgun equipped (essentially a friendly griefer Jesus instead of a hostile one.)

**Comment by Last0xygen** [comment] 2021-03-30 18:36
duplicate of #565, #391 #908 and #896

**Closed by Last0xygen** 2021-03-30 18:36 UTC
Labels: Effect Suggestion
