### ISSUE TITLE
[MetaEffect Suggestion] F*** you, chat

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#641] opened 2021-02-22 23:23 UTC
**Name of effect**
"F*** you, chat,"
"Dictatorship"
"Unpopular Decisions"

**Duration if timed effect (long or short timed?)**
 Long timed.

**Effect Description**
Choose the least popular vote instead of the most popular, or inverse percentages for proportional voting. Would have to be dependent on twitch integration.

**Comment by SeanMirrsen** [comment] 2021-03-03 22:57
Duplicate of #523 , no?

**Comment by Last0xygen** [comment] 2021-06-17 15:44
Duplicate #523

**Closed by Last0xygen** 2021-06-17 15:44 UTC
Labels: Effect Suggestion
