### ISSUE TITLE
[Effect Suggestion] Fake Crash Revamp

### ISSUE THREAD

**Issue by itsdereklol** [gta-chaos-mod/ChaosModV#1372] opened 2021-05-16 00:11 UTC
For the effect fake crash, I would like it to pull up the player’s home screen for a quick second, and then pull the game back up to make it even more believable.

**Comment by BitGhostYT** [comment] 2021-05-16 12:56
How would they put that into the mod, unless they had something where when you load the mod it would screenshot your Home Screen, but I don’t think that’s possible

**Comment by kolyaventuri** [comment] 2021-05-16 22:58
Closing as this is a duplicate of #1103

**Closed by kolyaventuri** 2021-05-16 22:58 UTC
Labels: Feature Request
