### ISSUE TITLE
All peds are animals

### ISSUE THREAD

**Issue by pinkomfg** [gta-chaos-mod/ChaosModV#260] opened 2020-12-15 18:02 UTC
When this effect occurs, everyone except the player becomes an animal. The animal they become is random. 
It shouldn’t affect them to do their things (animations, open doors, use weapons, etc.) in missions as they only look different.

**Comment by TheRealAyCe** [comment] 2020-12-15 20:19
Duplicate of this? https://github.com/gta-chaos-mod/ChaosModV/issues/253

**Closed** 2020-12-20 01:34 UTC
Labels: Effect Suggestion
