### ISSUE TITLE
[Effect Suggestion] Spawn Companion Jesse

### ISSUE THREAD

**Issue by AxmPlays** [gta-chaos-mod/ChaosModV#945] opened 2021-04-02 19:41 UTC
**Name of effect**
Spawn Companion Jesse/Jesus

**Effect Description**
It's Jesus with a railgun but doesn't attack you and defends you, just like Brad with an RPG.

**Comment by Last0xygen** [comment] 2021-04-02 19:42
duplicate of #565, #391 #908, https://github.com/gta-chaos-mod/ChaosModV/issues/910 and #896

**Closed by Last0xygen** 2021-04-02 19:42 UTC
Labels: Effect Suggestion
