### ISSUE TITLE
[Effect Suggestion] Wild Cat Appears

### ISSUE THREAD

**Issue by DeluxHDx** [gta-chaos-mod/ChaosModV#1668] opened 2021-06-29 18:20 UTC
Name of effect
Wild Cat Appears

Duration if timed effect (long or short timed?)
short/insta

Effect Description
Spawn aggresive Cougar behind a player.

**Comment by anto4440** [comment] 2021-06-29 19:33
Dupe of #916 and #1116

**Comment by Last0xygen** [comment] 2021-06-30 04:49
Yes, duplicate

**Closed by Last0xygen** 2021-06-30 04:49 UTC
Labels: Effect Suggestion
