### ISSUE TITLE
[Effect Suggestion] teleport to Light house 

### ISSUE THREAD

**Issue by Airtastik** [gta-chaos-mod/ChaosModV#824] opened 2021-03-17 22:38 UTC
**Name of effect**
Potential name(s) teleport to Lighthouse 

**Effect Description**
teleports player to the Lighthouse on the east side of the map

**Comment by anto4440** [comment] 2021-03-19 07:37
I cant find where it was previously, but this is literally a *copy paste* of a previous effect suggestion. why did you do this?

**Comment by Airtastik** [comment] 2021-03-20 03:24
It isn't, the other suggestion teleports to a different location.

**Comment by kolyaventuri** [comment] 2021-03-20 16:01
It isn't as obviously searchable, but this is a duplicate of #448, minus being in a tractor.

**Closed by kolyaventuri** 2021-03-20 16:01 UTC
Labels: Effect Suggestion
