### ISSUE TITLE
[Effect Suggestion] Unskippable Phone calls from online

### ISSUE THREAD

**Issue by TrayXCooper** [gta-chaos-mod/ChaosModV#3136] opened 2022-07-03 23:03 UTC
**Name of effect**
Ring Ring 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Have any random call u would get from gta online and make the calls unskippable

**Comment by pongo1231** [comment] 2022-07-03 23:37
Duplicate of #1119

**Closed by pongo1231** 2022-07-03 23:37 UTC
Labels: Effect Suggestion
