### ISSUE TITLE
[Effect Suggestion] Do A Barrel Roll!

### ISSUE THREAD

**Issue by Fansheep** [gta-chaos-mod/ChaosModV#769] opened 2021-03-10 13:59 UTC
**Name of effect**
Do A Barrel Roll!

**Duration if timed effect**
Short

**Effect Description**
Player's screen starts slowly rolling... Litteraly...

**Comment by TheRealAyCe** [comment] 2021-03-10 22:32
The vomit comet is back :D https://github.com/gta-chaos-mod/ChaosModV/issues/502

**Comment by anto4440** [comment] 2021-03-11 07:22
Wooohooo!
I wanna write 'Duplicate of XXX' this time!

**Comment by Last0xygen** [comment] 2021-03-11 07:23
Duplicate #502

**Closed by Last0xygen** 2021-03-11 07:23 UTC
Labels: Effect Suggestion

**Comment by Da-Best** [comment] 2021-03-11 07:51
Spinning camera is only the camera i thought of this as being front rolling over and over again? maybe just me miss understanding it
