### ISSUE TITLE
[Effect Suggestion] Aimbot

### ISSUE THREAD

**Issue by GerdTheAwesome** [gta-chaos-mod/ChaosModV#628] opened 2021-02-21 00:31 UTC
Aimbot
Potential name(s) for the effect
Insane Aimbot

**Duration if timed effect (long or short timed?)**
Mid

**Effect Description**
Gives the player insane aimbot and shot every one in the head. Automatic shot or the player have to shot him self

**Comment by Last0xygen** [comment] 2021-02-21 00:34
Already suggested. Please use the search before opening a new issue :) (https://github.com/gta-chaos-mod/ChaosModV/issues?q=Aimbot)
Duplicate of https://github.com/gta-chaos-mod/ChaosModV/issues/499

**Closed by Last0xygen** 2021-02-21 00:34 UTC
Labels: Effect Suggestion
