### ISSUE TITLE
Some Effects Ideas

### ISSUE THREAD

**Issue by CarlosX-The-Fire-FoxX** [gta-chaos-mod/ChaosModV#670] opened 2021-02-26 03:25 UTC
Ultra Griefer Jesus: The Griefer Jesus on Withe and Blue Toreador or a Withe and Blue Kanjali Tank

Online Companion: Spawn your online character as a companion with the WindowMaker Gun

Dubai Trafic: All NPCs will Spawn with randon super cars for a time like 1 or 2 minutes

Rubio's Revenge: Spawn EL Rubio with his helicopter and his guards trying to kill you

CyberPunk Police: Spawn random angry cops next to you with machine guns

**Comment by kolyaventuri** [comment] 2021-02-26 05:19
In general, try to submit effects as separate submissions. It takes a little more time, but it's much easier for us to track since we can implement each one individually as we have time and close them 1 by 1.

That being said though, Dubai Traffic sounds like a duplicate of #261, so maybe a name suggestion for the same idea? I tried my hand at implementing it once and it's super laggy due to all the replacements happening...

**Comment by anto4440** [comment] 2021-02-26 07:33
Bruh. All of these effects have been submittet before, and closed before for several reasons.

We dont need more Greifer Jesus. And its already been submittet. 5 times.

Online companion already covered with spawn random companion. Besides, we dont need more 'spawn ???'

Dubai traffic is the most hillarious one yet. Even I suggested this one, so its a duplicate of 2-3 other suggestions. Also, the engine cant handle it.

We dont need 'spawn ???'

And Cyberpunk police is covered with spawn random enemy

**Comment by Last0xygen** [comment] 2021-02-26 14:36
Everything is either already implemented (random traffic for example) or requested several times.
Also please create single requests for each effect as it’s hard to comment on several things in one Request

**Closed by Last0xygen** 2021-02-26 14:36 UTC
Labels: Effect Suggestion
