### ISSUE TITLE
[Effect Suggestion] Firework guns

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1189] opened 2021-04-27 09:20 UTC
**Name of effect**
Firework guns

**Duration if timed effect (long or short timed?)**
20 seconds

**Effect Description**
Makes fireworks come out of you guns, I tried this on my potato PC and it didn't crash GTA V

**Comment by anto4440** [comment] 2021-04-27 09:21
#1025

**Comment by anto4440** [comment] 2021-04-27 09:21
this is a bloody dupe of your own suggestion

**Comment by pipecek** [comment] 2021-04-27 09:24
frick
I forgot about it lmfao

**Closed** 2021-04-27 09:24 UTC
Labels: Effect Suggestion

**Comment by anto4440** [comment] 2021-04-27 09:26
Lmao
