### ISSUE TITLE
[Effect Suggestion] Ocean Man

### ISSUE THREAD

**Issue by ashgamer-06** [gta-chaos-mod/ChaosModV#603] opened 2021-02-18 06:12 UTC
**Name of effect**
Ocean Man

**Effect Description**
Teleport into random body of water

**Comment by kolyaventuri** [comment] 2021-02-18 06:13
Duplicate of #266 ?

**Comment by ashgamer-06** [comment] 2021-02-18 06:14
> Duplicate of #266 ?

Oh, didn't see that one.

**Comment by kolyaventuri** [comment] 2021-02-18 06:19
> > Duplicate of #266 ?
> 
> Oh, didn't see that one.

All good :+1: I'll close this one out

**Closed by kolyaventuri** 2021-02-18 06:19 UTC
Labels: Effect Suggestion
