### ISSUE TITLE
[Effect Suggestion] Spawn Extremely Angry Alien

### ISSUE THREAD

**Issue by YuBJrYT** [gta-chaos-mod/ChaosModV#3326] opened 2022-11-27 02:46 UTC
**Name of effect**
Spawn Extremely Angry Alien

Duration: Until Dead

**Effect Description**
it's just like the angry alien but instead it is red rather than green and spawns on the gun part of a "Technical Custom" and basically just tries it's best to annihilate you. This obviously takes inspiration from extreme griefer jesus! I also would love to see something likes this but with jealous jimmy
![TechnicalCustom-GTAO-front](https://user-images.githubusercontent.com/119144335/204116998-f95706e3-a343-477e-9631-7ffdad041b7b.jpg)

**Comment by anto4440** [comment] 2023-01-24 08:11
Dupe of #1917

**Comment by MoneyWasted** [comment] 2024-09-03 02:23
We are not currently adding "ped spawning" effects. (We have enough already.)

**Closed by MoneyWasted** 2024-09-03 02:23 UTC
Labels: Effect Suggestion
