### ISSUE TITLE
[Effect Suggestion] Davey!

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1151] opened 2021-04-24 08:30 UTC
**Name of effect**
Davey!

**Effect Description**
Spawns Dave as a companion with a carbine rifle equipped.

**Comment by pipecek** [comment] 2021-04-24 08:46
DUPLICATE of #18.

**Comment by Last0xygen** [comment] 2021-04-24 09:13
Yeah, duplicate #18

**Closed by Last0xygen** 2021-04-24 09:13 UTC
Labels: Effect Suggestion
