### ISSUE TITLE
[Effect Suggestion] Random Cutscene

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#1022] opened 2021-04-12 10:57 UTC
**Name of effect**
Random Cutscene

**Effect Description**
Play a random cutscene and force the player to watch it

**Comment by anto4440** [comment] 2021-04-12 11:09
Duplicate of #705

**Comment by Last0xygen** [comment] 2021-04-27 15:00
Duplicate

**Closed by Last0xygen** 2021-04-27 15:00 UTC
Labels: Effect Suggestion
