### ISSUE TITLE
[Effect Suggestion] Bullet rain

### ISSUE THREAD

**Issue by huskyplayer2001** [gta-chaos-mod/ChaosModV#707] opened 2021-03-02 22:44 UTC
**Name of effect**
Bullet rain, raining bullets, bullets of Jesus 

**Duration if timed effect (long or short timed?)**
A minute 

**Effect Description**
It should rain bullets from the sky onto the player like they’re being shot by a pistol a lot of times although it’s best to make the bullets not do too much damage otherwise it’ll be unplayable

**Comment by TheRealAyCe** [comment] 2021-03-03 00:54
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/238

**Comment by MoneyWasted** [comment] 2024-09-03 02:46
Duplicate of #238

**Closed by MoneyWasted** 2024-09-03 02:46 UTC
Labels: Effect Suggestion
