### ISSUE TITLE
Effect Suggestion

### ISSUE THREAD

**Issue by carpezax** [gta-chaos-mod/ChaosModV#598] opened 2021-02-17 08:12 UTC
Money Guns

30 seconds 

Spawns money bags that give you 2000$ when you shoot your gun

**Comment by TheRealAyCe** [comment] 2021-02-17 08:40
"The money shot"

**Comment by carpezax** [comment] 2021-02-17 08:41
That would be a good name for the effect, thanks for the reply

**Comment by kolyaventuri** [comment] 2021-02-17 15:51
Duplicate of #272

**Closed by kolyaventuri** 2021-02-17 15:51 UTC
Labels: Effect Suggestion
