### ISSUE TITLE
[Effect Suggestion] Called by Ms Baker

### ISSUE THREAD

**Issue by TrayXCooper** [gta-chaos-mod/ChaosModV#3133] opened 2022-07-03 21:36 UTC
**Name of effect**
Called by Ms. Baker

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Have Ms. Baker from online call you with those phone calls she gives you in gta online that are really annoying where she tells you she is the casino and resort manager and talks about the Duggans.
Make this phone call unskippable so you can't hang up if possible

**Comment by pongo1231** [comment] 2022-07-03 23:36
Duplicate of #1119

**Closed by pongo1231** 2022-07-03 23:36 UTC
Labels: Effect Suggestion
