### ISSUE TITLE
[Feature Suggestion] Discord Voting

### ISSUE THREAD

**Issue by AllanPrestYT** [gta-chaos-mod/ChaosModV#3365] opened 2023-02-17 04:55 UTC
add a discord voting system (this will need a discord bot token or the chaos mod bot) to vote it will send a message of what there is to vote and do 1. 2. 3. 4., like 1. jesus takes the wheel 2. fake death 3. fake crash 4. Spawn Griefer jesus

**Comment by pongo1231** [comment] 2023-02-23 22:50
Duplicate of #3053

**Closed by pongo1231** 2023-02-23 22:50 UTC
Labels: Feature Request
