### ISSUE TITLE
[Effect Suggestion] Good Christian Boy

### ISSUE THREAD

**Issue by PapaAquchala** [gta-chaos-mod/ChaosModV#2455] opened 2021-09-30 16:18 UTC
Name: Good Christian Boy OR Spawn Companion Jesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn griefer jesus that follows the player around but is actually friendly towards the player, and will join fights the player is currently in. Jesus is no longer useful when he dies or the player leaves him behind

**Comment by kolyaventuri** [comment] 2021-09-30 16:47
Duplicate of #391

**Closed by kolyaventuri** 2021-09-30 16:47 UTC
Labels: Effect Suggestion
